Monitor:
  Host: localhost
  Port: 5432
  User: autoctl_node
  Password: 123456
  DBName: pg_auto_failover
Coordinators:
  - DBName: postgres
    Password: 654321
    Username: postgres
    Formation: default
Settings:
  CheckInterval: 2000
  Debug: false
API:
  Enabled: true
  Port: 3002
  Secret: SECRET_STRING