Monitor:
  Host: localhost
  Port: 5432
  User: autoctl_node
  Password: 123456
  DBName: pg_auto_failover
Coordinator:
  Formation: default
  Password: 654321
  Username: postgres
  DBName: postgres
Settings:
  CheckInterval: 2000
  Debug: false
API:
  Enabled: true
  Port: 3002
  Secret: SECRET_STRING
